### ISSUE TITLE
Package error 

### ISSUE THREAD

**Issue by vikrams061** [mlukov/Viper-Android_Templates#1]
Hello Please i am not able to find these imports. from where you have added this if you have any reference for these packages pls provide

import com.snaps23.android.utils.StringUtils;
import com.snaps23.android.utils.FontUtils;

import android.printastic.com.imagepicker.ui.WaitDialog;
import android.printastic.com.imagepicker.handlers.BackHandlerInterface;
import android.printastic.com.imagepicker.handlers.BackHandlerObject;

**Comment by mlukov** [comment]
At first it was for internal company use, and these imports are leftovers from that time.
I have cleaned them up, get the newest version please.

**Comment by vikrams061** [comment]
Thanks now its working .
